

async def get_channel_metadata(channel_id, session):
	async with session.post("https://www.youtube.com/youtubei/v1/browse?prettyPrint=false&fields=alerts,metadata/channelMetadataRenderer(title,description,vanityChannelUrl,avatar/thumbnails(url,width,height)),header/pageHeaderRenderer/content/pageHeaderViewModel/metadata/contentMetadataViewModel/metadataRows/metadataParts/text/content", json = {"context": {"client": {"clientName": "WEB", "clientVersion": "2.20261007.01.00", "hl": "en"}}, "browseId": f"UC{channel_id}"}) as response:
		metadata = (lambda data: {"metadata_error": json.dumps(data.get("error") or data.get("alerts"), ensure_ascii = False) if data.get("error") or data.get("alerts") else "YouTube returned no channel metadata"} if data.get("error") or not data.get("metadata", {}).get("channelMetadataRenderer") else {"metadata_error": None, **{("name" if k == "title" else k): v for k, v in data["metadata"]["channelMetadataRenderer"].items() if k not in ("avatar", "vanityChannelUrl")}, "username": urllib.parse.unquote(data["metadata"]["channelMetadataRenderer"].get("vanityChannelUrl", "").rstrip("/").rsplit("/", 1)[-1]).removeprefix("@") or None, "avatar_url": max(data["metadata"]["channelMetadataRenderer"].get("avatar", {}).get("thumbnails", []), key = lambda image: image.get("width", 0) * image.get("height", 0), default = {}).get("url"), **{key: utils.convert_count_to_number(next((text for text in texts if word in text), "")) for texts in [[part.get("text", {}).get("content", "") for row in data.get("header", {}).get("pageHeaderRenderer", {}).get("content", {}).get("pageHeaderViewModel", {}).get("metadata", {}).get("contentMetadataViewModel", {}).get("metadataRows", []) for part in row.get("metadataParts", [])]] for key, word in [("subscriber_count", "subscriber"), ("video_count", "video")]}})(await response.json())
		print(json.dumps(metadata, indent = 2, ensure_ascii = False))
		return metadata


async def get_new_channel_videos(channel_id, existing_video_ids, session):
	async with session.post("https://www.youtube.com/youtubei/v1/browse?prettyPrint=false&fields=contents/twoColumnBrowseResultsRenderer/tabs/tabRenderer/content/sectionListRenderer/contents(itemSectionRenderer/contents(lockupViewModel/contentId,continuationItemViewModel/continuationCommand/innertubeCommand/continuationCommand/token),continuationItemViewModel/continuationCommand/innertubeCommand/continuationCommand/token)", json = {"context": {"client": {"clientName": "WEB", "clientVersion": "2.20261007.01.00"}}, "browseId": f"VLUU{channel_id}"}) as response:
		video_ids, token = (lambda items: ([i["lockupViewModel"]["contentId"] for i in items if "lockupViewModel" in i], next((i["continuationItemViewModel"]["continuationCommand"]["innertubeCommand"]["continuationCommand"]["token"] for i in items if "continuationItemViewModel" in i), None)))((await response.json())["contents"]["twoColumnBrowseResultsRenderer"]["tabs"][0]["tabRenderer"]["content"]["sectionListRenderer"]["contents"][0]["itemSectionRenderer"]["contents"])
		return video_ids, token